import Head from 'next/head'
import React from 'react'
import classnames from 'classNames'
import styles from '../styles/Home.module.css'
import pic from '../public/IMG_6534.JPG'
import Image from 'next/image'

export default function Home() {
  const [start, setStart] = React.useState(false);
  const act = ['code', 'swim', 'jump', 'draw', 'love', 'pray', 'fish', 'care'];
  const [i, seti] = React.useState(5)
  React.useEffect(() => {
      const timer =
        i > 0 && setInterval(() => seti(i + 1), 1000);
      return () => clearInterval(timer);
    }, [i]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={start&&styles.updiv}>
        <h1 className={styles.title}>
          Hello!
        </h1>

        <h1 className={styles.title}>
          My name is Pascal
        </h1>
        </div>

        <br></br>

        <button className={classnames(styles.hover, start&&styles.hoverAfter)} onClick={() => setStart(true)} start={start}>click me</button>
        
        <Image src={pic} width='600' height='400' className={classnames(styles.imgHide, start&&styles.imgAfter)}/>

        <div className={start&&styles.downdiv}>
        <p className={styles.description}>
          Currently I'm learning how to
          <code className={styles.code}>{act[i%act.length]}</code>
        </p>
        </div>

        <div>

        </div>

      </main>
    </div>
  )
}
